[mastr-data]

url = "https://sandbox.zenodo.org/record/{}/files/"
deposit_id = 1132987
dump_date = "2022-11-17"
f_name = "bnetza_mastr_{}_cleaned.csv"
f_name_2 = "location_elec_generation_raw.csv"
technologies = [
    "solar",
    "wind",
    "hydro",
    "biomass",
    "combustion",
    "nuclear",
    "gsgk",
    "storage",
]
federal_state = "Everything"
epsg = 4326

[geocoding]

user_agent = "rli_kh_geocoder"
min_delay_seconds = 1
export_f = "mastr_geocoding_{}_{}.gpkg"
