[mastr-data]

url = "https://zenodo.org/records/{}/files/"
deposit_id = 10491882
dump_date = "2024-01-08"
f_name = "bnetza_mastr_{}_cleaned.csv"
technologies = [
    "solar",
    "wind",
    "hydro",
    "biomass",
    "combustion",
    "nuclear",
    "gsgk",
    "storage",
]
federal_state = "Everything"
epsg = 4326

[geocoding]

user_agent = "rli_kh_geocoder"
min_delay_seconds = 1
export_f = "mastr_geocoding_{}_{}.gpkg"
